---
title: "Problem set 1"
subtitle: "PPHA 32400 Microeconomics and Public Policy II"
author: "Jay Ballesteros"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

## 1. Consider a profit-maximizing firm with a marginal cost function given by MC(q) = 10 + q. It is a perfectly competitive firm i.e. it is a price-taker. The market price is p.

**a) Consider a situation where the firm is already in the market. What is the optimal quantity to produce? (Hint: the optimal quantity will be a function of p.)**

**b) Consider a situation where the firm is already in the market. Depict the marginal cost curve graphically, with the quantity produced on the x-axis and the prices/costs on the y-axis. Label the intercepts, as well as the optimal quantity. Label the producer surplus. Assume that the firm is already in the market. What is the producer surplus earned by the firm? You may assume that p \> 10. (Hint: The producer surplus will be a function of p.)**

**c) Consider a situation where the the firm is deciding whether to enter the market or not. Suppose that the fixed cost is FC= 50. What is the price below which the firm will not enter the market. (Hint: the firm will enter the market if it’s profit π is positive. Profit is producer surplus minus the fixed cost i.e. π = PS−FC**

**d) If the fixed cost is FC= 50 (as it was in the previous question) what is the firm’s supply function? Depict it graphically, with the price on the y-axis, and quantity on the x-axis. Label any kinks in the curve**
